<!DOCTYPE html>
<html>
<head>
{template public/WxShareJS}
	<meta charset="UTF-8">
	<title>掌玩APP--关于我们</title>
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/mobile.css?2017050910">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="format-detection" content="telephone=no">
	<!-- UC默认竖屏 ，UC强制全屏 -->
	<meta name="full-screen" content="yes">
	<meta name="browsermode" content="application">
	<!-- QQ强制竖屏 QQ强制全屏 -->
	<meta name="x5-orientation" content="portrait">
	<meta name="x5-fullscreen" content="true">
	<meta name="x5-page-mode" content="app">
	<meta name="format-detection" content="email=no">
	<style>
		.content{max-width: 720px;margin: 0 auto;}
		.content img{max-width: 100%;}
		.Footer img{float: left;width: 50%;}
	</style>
</head>
<body>
	<div class="content">
		<img src="{$CDN_BASE_URL_RES}/html/images/about01.jpg">
		<img src="{$CDN_BASE_URL_RES}/html/images/about02.jpg">
		<img src="{$CDN_BASE_URL_RES}/html/images/about03.jpg">
		<img src="{$CDN_BASE_URL_RES}/html/images/about04.jpg">
		<img src="{$CDN_BASE_URL_RES}/html/images/about05.jpg">
		<footer class="Footer">
			<img src="{$CDN_BASE_URL_RES}/html/images/about06.jpg?171102">
			<img src="{$CDN_BASE_URL_RES}/html/images/about07.jpg">
		</footer>
	</div>
</body>
</html>