<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
    <title>掌玩APP下载</title>
    <link href="https://cdn.bootcss.com/Swiper/4.3.0/css/swiper.min.css" rel="stylesheet">
    <script src="https://res.wx.qq.com/open/js/jweixin-1.3.2.js"></script>
    <style>
        html,
        body {
            position: relative;
            height: 100%;
            width: 100%;
            overflow: hidden;
        }

        body {
            background: #eee;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #000;
            margin: 0;
            padding: 0;
        }

        .swiper-container {
            width: 100%;
            height: 100%;
        }

        .swiper-slide {
            text-align: center;
            font-size: 18px;
            background: #fff;

            /* Center slide text vertically */
            display: -webkit-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            -webkit-justify-content: center;
            justify-content: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            -webkit-align-items: center;
            align-items: center;
        }
        .swiper-slide img{
            display: block;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
        }
        .downBtn{
            display: block;
            position: absolute;
            left: 50%;
            bottom: 36px;
            width: 80%;
            height: 100px;
            margin-left: -40%;
            z-index: 999;
        }
        .downBtn img{
            display: block;
            width: 100%; height: auto;
        }
        .mask{
            z-index: 9999;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0,0,0,0.5);
            display:none;
        }
        .mask img{
            width: 95%;
            float: right;
            margin-right: 10px;
        }
    </style>
    <script>
        wx.config({
          debug: false,
          appId: "{$wxJsConfig['appId']}",
          timestamp: {$wxJsConfig['timestamp']},
          nonceStr: "{$wxJsConfig['noncestr']}",
          signature: "{$wxJsConfig['signature']}",
          jsApiList: [
            // 所有要调用的 API 都要加到这个列表中
            'onMenuShareTimeline',
            'onMenuShareAppMessage'
          ]
        });
    </script>
</head>

<body>

    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <img src="https://zhangwan-static.oss-cn-hangzhou.aliyuncs.com/h5/download1.png" alt="掌玩APP下载"/>
            </div>
            <div class="swiper-slide">
                <img src="https://zhangwan-static.oss-cn-hangzhou.aliyuncs.com/h5/download2.png" alt="掌玩APP下载" />
            </div>
            <div class="swiper-slide">
                <img src="https://zhangwan-static.oss-cn-hangzhou.aliyuncs.com/h5/download3.png" alt="掌玩APP下载" />
            </div>
            <div class="swiper-slide">
                <img src="https://zhangwan-static.oss-cn-hangzhou.aliyuncs.com/h5/download4.png" alt="掌玩APP下载" />
            </div>
        </div>
    </div>

    <div class="downBtn">
        <img src="https://zhangwan-static.oss-cn-hangzhou.aliyuncs.com/miniprogram/btn.png"/>
    </div>
    <div class="mask" id="down">
        <img src= "http://zhangwan-picture-prod.oss-cn-hangzhou.aliyuncs.com/aliyun_oss/activity_images/201809/21/16534132157.png" alt="">
    </div>
    <script src="https://cdn.bootcss.com/Swiper/4.3.0/js/swiper.min.js"></script>

    <script>
        var swiper = new Swiper('.swiper-container', {
            loop: true,
            autoplay: {
                delay: 2000
            }
        });
        // var u = navigator.userAgent;
        // var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);
        var BTN = document.querySelector('.downBtn');
        BTN.addEventListener('click', function () {
            if (/MicroMessenger/i.test(navigator.userAgent)) {
            //ios的ua中无miniProgram，很坑爹,但都有MicroMessenger（表示是微信浏览器）
                wx.miniProgram.getEnv((res)=>{
                    if (res.miniprogram) {
                        return alert('请前往应用商店下载');
                    } else{
                        // 提示弹窗下载
                        // alert ()
                        var downTip = document.getElementById("down")
                        downTip.style.display = 'block'
                    }
                })
                }else{
                    var userAgent = navigator.userAgent;
                    var isAndroid = userAgent.indexOf('Android') > -1 || userAgent.indexOf('Adr') > -1; //android终端
                    var isiOS = !!userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
                    if(isAndroid){
                        window.location.href = 'https://cdn.16988.cn/res/download/app/handplay_release.apk'
                    }else if(isiOS){
                        window.location.href = 'http://a.app.qq.com/o/simple.jsp?pkgname=art.jupai.com.jupai'
                    }
                }
            
        });
        try {
            wx.ready(function () {
                // 分享到朋友圈
                var titem = '掌玩APP——懂生活，有艺术！';
                var desc = '专业的艺术品交易交流分享平台，让艺术融入生活，让生活充满艺术。';
                var imgurl = 'http://pp.myapp.com/ma_icon/0/icon_52440266_1528191472/96';
                wx.onMenuShareTimeline({
                    title: titem,
                    desc: desc,
                    link: window.location.href,
                    imgUrl: imgurl,
                    success: function (res) {
                        // console.log('分享到朋友圈成功返回的信息为:', res);
                    },
                    cancel: function (res) {
                        // console.log('取消分享到朋友圈返回的信息为:', res);
                    }
                });
                //分享给朋友
                wx.onMenuShareAppMessage({
                    title: titem,
                    desc: desc,
                    link: window.location.href,
                    imgUrl: imgurl,
                    success: function (res) {
                        // console.log('分享到朋友圈成功返回的信息为:', res);
                    },
                    cancel: function (res) {
                        // console.log('取消分享到朋友圈返回的信息为:', res);
                    }
                });
            });
        } catch (err) { }
    </script>
</body>

</html>
