<!DOCTYPE html>
<html>
<head>
{template public/WxShareJS}
	<meta charset="UTF-8">
	<title>【掌玩报道】第十届禹州·中国钧瓷文化旅游节 名家专访</title>
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="format-detection" content="telephone=no">
	<meta name="full-screen" content="yes">
	<meta name="browsermode" content="application">
	<meta name="x5-orientation" content="portrait">
	<meta name="x5-fullscreen" content="true">
	<meta name="x5-page-mode" content="app">
	<meta name="format-detection" content="email=no">
	<meta name="msapplication-tap-highlight" content="no">
	<link rel="stylesheet" type="text/css" href="{$CDN_BASE_URL_RES}/html/css/zhuanti.css?v=1.6">
	<script src="{$CDN_BASE_URL_RES}/html/js/lib/require.js" data-main="{$CDN_BASE_URL_RES}/html/js/work/celebrity.js?v=2.4"></script>
</head>
<body>
	<img src="{$CDN_BASE_URL_RES}/html/images/banner.jpg" class="img">
	<a href="#" class="home"><img src="{$CDN_BASE_URL_RES}/html/images/home.png"></a>
	<!-- 名家专访 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t5.gif" class="img">
		<div class="font">
			<ul class="list1 list3" id="list2">
				
			</ul>
			<div class="more">
	        展开更多<br><img src="{$CDN_BASE_URL_RES}/html/images/more.png?v=1.0">
	      </div>
		      <input type="hidden" id="page" name="" value="2">
		      <input type="hidden" id="pagesize" name="" value="6">
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/bottom.jpg" class="img" style="margin-top: 2rem;">
	
</body>
</html>