<!doctype html>
<html lang="en">
<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="format-detection" content="telephone=no" />
    <script src="{$CDN_BASE_URL_RES}/html/js/work/fontSize.min.js"></script>
    <title>证书</title>
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/public.min.css">
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/credential.min.css">
    <script src="{$CDN_BASE_URL_RES}/html/js/lib/require.js" data-main="{$CDN_BASE_URL_RES}/html/js/work/credential.min.js?v=1.0"></script>
</head>
<body class="padding clearfix">
    <h3 id="title">证明书</h3>
    <div id="img">
        <img id="itemImage" src="./images/credentia-img.png" alt="证书">
    </div>
    <table>
        <tr>
            <td>作品编号：</td>
            <td id="g_sn">123456789112</td>
        </tr>
        <tr>
            <td>作品名称：</td>
            <td id="g_name">远方的山坡</td>
        </tr>
        <tr>
            <td>作者：</td>
            <td id="gu_realname">王舞</td>
        </tr>
        <tr>
            <td>作品尺寸：</td>
            <td id="g_size">50*90cm</td>
        </tr>
        <tr>
            <td>创作年份：</td>
            <td id="g_madeTime">2017</td>
        </tr>
    </table>
    <div class="clearfix" id="signature">
        <div class="fr">
            <p>公证机构签章：</p>
            <p>发证日期：<span id="time">2017年5月20日</span></p>
        </div>
    </div>
    <div class="warm">
        <p>掌玩证明：</p>
        <p>掌玩平台上的艺术家，均为掌玩签约认证艺术家。平台展示销售的艺术品，均为艺术家本人真品，永久保真，假一赔十。</p>
        <div class="bottom-img"></div>
    </div>
</body>
</html>