<!DOCTYPE html>
<html lang="zh">
<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1,user-scalable=no">
    <title>敬请期待</title>
    <style type="text/css">
        body{
            width: 100%;
            max-width: 768px;
        }
        *{margin: 0;padding: 0;}
        img{width: 35%;margin: 24% auto;display: block;}
    </style>
</head>
<body>
    <img src="{$CDN_BASE_URL_RES}/html/images/qidai.png">
</body>
</html>