<!DOCTYPE html>
<html>
<head>
{template public/WxShareJS}
<meta charset="UTF-8">
<title>掌玩APP下载页</title>
<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/pc.css?20170310">
<script src="{$CDN_BASE_URL_RES}/html/js/jquery.min.js"></script>
</head>
<body>
<div class="ju">
	<div class="navBox">
		<div class="nav">
			<img class="logo" src="{$CDN_BASE_URL_RES}/html/images/logo.png?20170331">
			<div class="aLink">
				<a class="on" href="javascript:;">首页</a>
				<a href="javascript:;">艺术商城</a>
				<a href="javascript:;">好友社群</a>
				<a href="javascript:;">晒宝社区</a>
				<a href="javascript:;">发现应用</a>
				<a href="javascript:;">扫码下载</a>
			</div>
			<div class="phone">
				<img src="{$CDN_BASE_URL_RES}/html/images/ico_01.png">
				<i>400-886-9956</i>
			</div>
		</div>
	</div>
	<div class="bigBox">
		<div class="page page1">
<div class="pag1Box pageBox">
	<div class="txt">
		<h3>下载掌玩APP</h3>
		<p>让艺术走进生活！</p>
	</div>
	<div class="p1_btn">
		<a class="a1" href="https://itunes.apple.com/cn/app/%E6%8E%8C%E7%8E%A9/id1225131835?mt=8">
			<img src="{$CDN_BASE_URL_RES}/html/images/AAP.png"></a>
		<a class="a2" href="https://cdn.16988.cn/res/download/app/handplay_release.apk">
			<img src="{$CDN_BASE_URL_RES}/html/images/Android.png"></a>
		<a class="a3" href="javascript:;"><img src="{$CDN_BASE_URL_RES}/html/images/Ama.png">
			<img src="{$CDN_BASE_URL_RES}/html/images/erweima.png?20170525" class="img02">
		</a>
	</div>
	<img class="img01" src="{$CDN_BASE_URL_RES}/html/images/p1_1.png?20170503">
</div>
		</div>
		<div class="page page2">
<div class="pag2Box pageBox">
	<div class="txt">
		<h2>艺术商城</h2>
		<h4>真迹藏品应有尽有</h4>
		<p>掌玩APP提供专业的艺术品交易平台，让艺术品走进寻常百姓家，让热爱艺术的人与艺术近在咫尺，也让艺术家衣食无忧！</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p2_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page3">
<div class="pag3Box pageBox">
	<div class="txt">
		<h2>兴趣社交</h2>
		<h4>好友社群在线互动</h4>
		<p>让懂艺术的人更懂你，让你更了解懂艺术的人，兴趣爱好者的聚集地，兴趣交友，同行交流，专业的艺术品交流APP。</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p3_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page4">
<div class="pag4Box pageBox">
	<div class="txt">
		<h2>晒宝社区</h2>
		<h4>友赞评论艺术天地</h4>
		<p>不孤芳自赏，有宝贝，晒一晒，与大家分享，不一样的朋友圈，点赞，评论、吐槽，掌玩APP给你不一样的体验和惊喜。</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p4_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page5">
<div class="pag5Box pageBox">
	<div class="txt">
		<h2>附近发现</h2>
		<h4>名家真品近在咫尺</h4>
		<p>你身边的艺术品，交藏友，约名家，求定制，看不一样的艺术世界。 相识满天下,知心能几人，让你的艺术生活从此不再孤单！</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p5_1.png?20170331" class="img01">
</div>
		</div>
		<div class="bottom page6">
<div class="pag6Box pageBox">
	<div class="top">
		<img src="{$CDN_BASE_URL_RES}/html/images/logo_bottom.png?20170331" class="foootLogo" alt="">
		<div class="phone">
			<img src="{$CDN_BASE_URL_RES}/html/images/ico_02.png" class="img01">
			<div class="tx">
				<div>400-886-9956</div>
				<p>免费客服热线</p>
			</div>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="saoma">
			<img src="{$CDN_BASE_URL_RES}/html/images/gongzhonghao.jpg" class="img02">
			<div>
				<p>扫码关注公众号</p>
				<p>微信号:fyqt66</p>
			</div>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="saoma">
			<img src="{$CDN_BASE_URL_RES}/html/images/erweima.png?20170525" class="img02">
			<div>
				<p>扫描二维码</p>
				<p>下载APP</p>
			</div>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="linkBtn">
			<a href="https://cdn.16988.cn/res/download/app/handplay_release.apk">
				<img src="{$CDN_BASE_URL_RES}/html/images/p6_1.png" alt="">
			</a>
			<a href="https://itunes.apple.com/cn/app/%E6%8E%8C%E7%8E%A9/id1225131835?mt=8">
				<img src="{$CDN_BASE_URL_RES}/html/images/p6_2.png" alt="">
			</a>
		</div>
	</div>
	<p class="bottom">Copyright © 2008-2017 河南九阳网络科技有限公司 </p>
</div>
		</div>
	</div>
	<div class="btnBox">
		<div class="showBtn">
			<span class="s1"></span>
			<span class="s2"></span>
			<span class="s3"></span>
			<span class="s4"></span>
			<span class="s5"></span>
			<span class="s6"></span>
		</div>
		<div class="moveBtn s1"></div>
	</div>
</div>
<script>
var nowPage = 1;
var timer1 = new Date();
$(document).on("mousewheel DOMMouseScroll", function (e) {
    var delta = (e.originalEvent.wheelDelta && (e.originalEvent.wheelDelta > 0 ? 1 : -1)) || (e.originalEvent.detail && (e.originalEvent.detail > 0 ? -1 : 1));
    var timer2 = new Date();
    if(timer2-timer1>700)
    {
    	if (delta > 0) {
    		timer1 = timer2;
	        // 向上滚
	        wheelup();
	    } else if (delta < 0) {
	        // 向下滚
	        timer1 = timer2;
	       wheeldown();
	    };
    };
});
var oBig = $(".bigBox");
var oshowBtn = $(".showBtn");
var omoveBtn = $(".moveBtn");
var opage = $(".bigBox .page");
oshowBtn.find('span').click(function(event) {
	var ind = $(this).index();
	nowPage = ind+1;
	move1(nowPage);
});
$(".aLink a").click(function(event) {
	var ind = $(this).index();
	nowPage = ind+1;
	move1(nowPage);
});
move2(nowPage);
function wheelup()
{
	if(nowPage == 1)
	{
		return;
	};
	nowPage --;
	move1(nowPage);
};
function wheeldown()
{
	if(nowPage == 6)
	{
		return;
	};
	nowPage ++;
	move1(nowPage);
};
function move2(ind)
{
	oBig.attr("class","bigBox pageMove"+ind);
	omoveBtn.attr("class","moveBtn s"+ind);
	$(".aLink a").removeClass('on');
	$(".aLink a").eq(ind-1).addClass('on');
	setTimeout(function(){
		opage.find('.pageBox').removeClass('pagMove');
		opage.eq(ind-1).find('.pageBox').attr("class","pag"+ind+"Box pageBox pagMove");
	},200);
}
function move1(ind)
{
	oBig.attr("class","bigBox pageMove"+ind);
	omoveBtn.attr("class","moveBtn s"+ind);
	$(".aLink a").removeClass('on');
	$(".aLink a").eq(ind-1).addClass('on');
	setTimeout(function(){
		if(ind>5){ind=5};
		opage.find('.pageBox').removeClass('pagMove');
		opage.eq(ind-1).find('.pageBox').attr("class","pag"+ind+"Box pageBox pagMove");
	},500);
};
</script>
</body>
</html>