<!DOCTYPE html>
<html>
<head>
{template public/WxShareJS}
<meta charset="UTF-8">
<title>掌玩APP下载页</title>
<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/mobile.css?2017050910">
<script src="{$CDN_BASE_URL_RES}/html/js/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
<meta http-equiv="Content-Type" content="text/html">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="format-detection" content="telephone=no">
<!-- UC默认竖屏 ，UC强制全屏 -->
<meta name="full-screen" content="yes">
<meta name="browsermode" content="application">
<!-- QQ强制竖屏 QQ强制全屏 -->
<meta name="x5-orientation" content="portrait">
<meta name="x5-fullscreen" content="true">
<meta name="x5-page-mode" content="app">
<meta name="format-detection" content="email=no">
</head>
<body>
<div class="ju">
	<div class="bigBox">
		<div class="page page1">
<div class="pag1Box pageBox">
	<div class="txt">
		<img width="33%" src="{$CDN_BASE_URL_RES}/html/images/logo.png?20170331" class="mlogo">
		<h3>下载掌玩APP</h3>
	</div>
	<div class="p1_btn">
		<!-- <a class="a1 phonebtn" href="https://itunes.apple.com/cn/app/%E6%8E%8C%E7%8E%A9/id1225131835?mt=8">
			<img src="{$CDN_BASE_URL_RES}/html/images/AAP.png"></a> -->
		<a class="xiazai">立即下载</a>
		<!-- <a class="a2 androidbtn">
			<img src="{$CDN_BASE_URL_RES}/html/images/Android.png">
		</a> -->
	</div>
	<img class="img01" src="{$CDN_BASE_URL_RES}/html/images/p1_1.png?20170331">
</div>
		</div>
		<div class="page page2">
<div class="pag2Box pageBox">
	<div class="txt">
		<h2>艺术商城</h2>
		<h4>真迹藏品应有尽有</h4>
		<p>掌玩APP提供专业的艺术品交易平台，让艺术品走进寻常百姓家，让热爱艺术的人与艺术近在咫尺，也让艺术家衣食无忧！</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p2_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page3">
<div class="pag3Box pageBox">
	<div class="txt">
		<h2>兴趣社交</h2>
		<h4>好友社群在线互动</h4>
		<p>让懂艺术的人更懂你，让你更了解懂艺术的人。兴趣爱好者的聚集地，兴趣交友，同行交流，专业的艺术品交流APP。</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p3_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page4">
<div class="pag4Box pageBox">
	<div class="txt">
		<h2>晒宝社区</h2>
		<h4>友赞评论艺术天地</h4>
		<p>不孤芳自赏，有宝贝，晒一晒，与大家分享，不一样的朋友圈，点赞，评论、吐槽，掌玩APP给你不一样的体验和惊喜。</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p4_1.png?20170331" class="img01">
</div>
		</div>
		<div class="page page5">
<div class="pag5Box pageBox">
	<div class="txt">
		<h2>附近发现</h2>
		<h4>名家真品近在咫尺</h4>
		<p>你身边的艺术品，交藏友，约名家，求定制，看不一样的艺术世界。 相识满天下,知心能几人，让你的艺术生活从此不再孤单！</p>
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/p5_1.png?20170331" class="img01">
</div>
		</div>
		<div class="bottom page6">
<div class="pag6Box pageBox">
	<div class="top">
		<img src="{$CDN_BASE_URL_RES}/html/images/logo_bottom.png?20170331" class="foootLogo" alt="">
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="linkBtn">
			<!-- <a class="androidbtn">
				<img src="{$CDN_BASE_URL_RES}/html/images/p6_1.png" alt="">
			</a>
			<a href="javascript:;" class="phonebtn">
				<img src="{$CDN_BASE_URL_RES}/html/images/p6_2.png" alt="">
			</a> -->
			<a class="xiazai">立即下载</a>
			<div class="tx">
				<div>400-886-9956</div>
				<p>免费客服热线</p>
			</div>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="saoma">
			<img src="{$CDN_BASE_URL_RES}/html/images/gongzhonghao.jpg" class="img02">
			<div>
				<p>扫码关注公众号</p>
				<p>微信号:fyqt66</p>
			</div>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/p6_3.png" class="img03">
		<div class="saoma">
			<img src="{$CDN_BASE_URL_RES}/html/images/erweima.png?20170525" class="img02">
			<div>
				<p>扫描二维码</p>
				<p>下载APP</p>
			</div>
		</div>
		
	</div>
	<p class="bottom">Copyright © 2008-2017 河南九阳网络科技有限公司 </p>
</div>
		</div>
	</div>
	<div class="btnBox">
		<div class="showBtn">
			<span class="s1"></span>
			<span class="s2"></span>
			<span class="s3"></span>
			<span class="s4"></span>
			<span class="s5"></span>
			<span class="s6"></span>
		</div>
		<div class="moveBtn s1"></div>
	</div>
</div>
<script>
var nowPage = 1;
$(document).bind("touchstart","",fn_touchstart);
$(document).bind("touchmove","",fn_touchmove);
$(document).bind("touchend","",fn_touchend);
// $(".androidbtn").bind("touchend","",fn_android);
// $(".phonebtn").bind("touchend","",fn_phone);
// function fn_phone()
// {
// 	location = "https://itunes.apple.com/cn/app/%E6%8E%8C%E7%8E%A9/id1225131835?mt=8";
// };
// function fn_android()
// {
// 	var ua = navigator.userAgent.toLowerCase();
// 	var isWeixin = ua.indexOf('micromessenger') != -1;
// 	if(isWeixin){
// 		alert("请点击右上角在浏览器中打开下载app");
// 	}else{
// 		location = "https://cdn.16988.cn/res/download/app/handplay_release.apk";
// 	}
	
// };

$(".xiazai").bind("touchend",function(){
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
	var ua = navigator.userAgent.toLowerCase();
	var isWeixin = ua.indexOf('micromessenger') != -1;
	if(isiOS){
		if(isWeixin){
			alert("请点击右上角在浏览器中打开下载app");
		}else{
			location = "https://itunes.apple.com/cn/app/%E6%8E%8C%E7%8E%A9/id1225131835?mt=8";
		}
	}else if(isAndroid){
		if(isWeixin){
			alert("请点击右上角在浏览器中打开下载app");
		}else{
			location = "https://cdn.16988.cn/res/download/app/handplay_release.apk";
		}
	}
});


var nowY;
function fn_touchstart()
{
	var touch = event.changedTouches[0];
	nowY= touch.clientY;
	event.preventDefault();
};
function fn_touchmove()
{
	event.preventDefault();
};
function fn_touchend()
{
	var touch = event.changedTouches[0];
	var nowY1= touch.clientY;
	//console.log("nowY1="+nowY1+"////"+"nowY="+nowY1);
	if(nowY1-nowY>15)
	{
		wheelup();
	};
	if(nowY-nowY1>15)
	{
		wheeldown();
	};
};
var oBig = $(".bigBox");
var oshowBtn = $(".showBtn");
var omoveBtn = $(".moveBtn");
var opage = $(".bigBox .page");
oshowBtn.find('span').each(function(index, el) {
	$(this).bind("touchstart","",fn_touchend1);
});
function fn_touchend1()
{
	var ind = $(this).index();
	nowPage = ind+1;
	move1(nowPage);
	event.preventDefault();
	return false;
};
move2(nowPage);
function wheelup()
{
	if(nowPage == 1)
	{
		return;
	};
	nowPage --;
	move1(nowPage);
};
function wheeldown()
{
	if(nowPage == 6)
	{
		return;
	};
	nowPage ++;
	move1(nowPage);
};
function move2(ind)
{
	oBig.attr("class","bigBox pageMove"+ind);
	omoveBtn.attr("class","moveBtn s"+ind);
	$(".aLink a").removeClass('on');
	$(".aLink a").eq(ind-1).addClass('on');
	setTimeout(function(){
		opage.find('.pageBox').removeClass('pagMove');
		opage.eq(ind-1).find('.pageBox').attr("class","pag"+ind+"Box pageBox pagMove");
	},200);
}
function move1(ind)
{
	oBig.attr("class","bigBox pageMove"+ind);
	omoveBtn.attr("class","moveBtn s"+ind);
	$(".aLink a").removeClass('on');
	$(".aLink a").eq(ind-1).addClass('on');
	setTimeout(function(){
		if(ind>5){ind=5};
		opage.find('.pageBox').removeClass('pagMove');
		opage.eq(ind-1).find('.pageBox').attr("class","pag"+ind+"Box pageBox pagMove");
	},500);
};
</script>
</body>
</html>