<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimum-scale=1, maximum-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="format-detection" content="telephone=no, email=no">
  <meta name="renderer" content="webkit">
  <meta name="force-rendering" content="webkit">
  <title></title>
  <link rel="stylesheet" href="{$DOMAIN_APP}/res/html/preApply/index.min.css?v=1" type="text/css"/>
  <script type="text/javascript" src="https://s29.9956.cn/res/crowdsource/lib/vue.min.js?v=1"></script>
  <script type="text/javascript">
    //静态资源设置路径
    // window.resourceBaseUrl = 'http://dev-cdn.zhangwan.shop/res/html/'; //测试环境路径
      window.resourceBaseUrl = '{$DOMAIN_APP}/res/html/'; //线上环境路径
    //  window.resourceBaseUrl = 'https://app.16988.cn/res/html/';
  </script>
</head>
<body>
  <div id="app"></div>
  <script type="text/javascript" src="{$DOMAIN_APP}/res/html/preApply/index.min.js?v=1"></script>
</body>
</html>