<!doctype html>
<html lang="en">
<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{$CDN_BASE_URL_RES}/html/js/work/fontSize.min.js"></script>
    <title>常见问题</title>
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/public.min.css">
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/problem.min.css?v=1.0">
    <script src="{$CDN_BASE_URL_RES}/html/js/lib/require.js?171219" data-main="{$CDN_BASE_URL_RES}/html/js/work/problem.js?171219"></script>
</head>
<body>
    <ul class="p-list-box return">
        <li class="padding" data-type="aboutApprove"><h4>关于认证</h4></li>
        <li class="padding" data-type="FAQ"><h4>常见问题</h4></li>
        <li class="padding" data-type="preProblem"><h4>售前问题</h4></li>
        <li class="padding" data-type="saleProblem"><h4>售中问题</h4></li>
        <li class="padding" data-type="afterProblem"><h4>售后问题</h4></li>
    </ul>
    <h3 class="padding">联系客服</h3>
    <ul class="p-list-box talk">
       <!--  <li class="padding" id="keFu">在线客服</li> -->
        <li class="clearfix padding" id="phone">
            <div class="fl">客服热线</div>
            <div class="fr"><a href="tel:0371-88889956">0371-88889956</a></div>
        </li>
    </ul>
    <ul class="p-list-box user-protocol">
        <li class="padding" id="user-protocol">用户协议</li>
    </ul>
</body>
</html>