<!doctype html>
<html lang="en">
<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{$CDN_BASE_URL_RES}/html/js/work/fontSize.min.js"></script>
    <title></title>
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/public.min.css">
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/problem.min.css">
    <script src="{$CDN_BASE_URL_RES}/html/js/lib/require.js" data-main="{$CDN_BASE_URL_RES}/html/js/work/problemDetail.js"></script>
</head>
<body >
    <div class="problemDetail clearfix">
        <h3 id="d-title"></h3>
        <div class="padding" id="content"></div>
    </div>
</body>
</html>