<!doctype html>
<html lang="zh">
<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
    <title>限时抢购</title>
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/seckill/css/global.css">
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/seckill/css/index.css">
    <script src="//s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
    <script src="{$CDN_BASE_URL_RES}/html/seckill/js/index.js?0125"></script>
</head>

<body>
    <div class="wrap">
        <header>
            <img src="{$CDN_BASE_URL_RES}/html/seckill/images/content_01.png" alt="">
        </header>
        <div class="countDown">
            <div class="center">
                <h2>距离开始还有</h2>
                <img src="{$CDN_BASE_URL_RES}/html/seckill/images/timer.png" class="timer" alt="">
                <ul class="clearfix">
                    <li>00</li>
                    <li>天</li>
                    <li>00</li>
                    <li>时</li>
                    <li>00</li>
                    <li>分</li>
                    <li>00</li>
                    <li>秒</li>
                </ul>
            </div>
        </div>
        <div class="conduct">
            <img src="{$CDN_BASE_URL_RES}/html/seckill/images/content_03.png" alt="">
        </div>
        <div class="product">
            <ul class="center">
          
            </ul>
        </div>
    </div>
 
</body>

</html>