<!DOCTYPE html>
<html>
<head>
{template public/WxShareJS}
	<meta charset="UTF-8">
	<title>第十届禹州·中国钧瓷文化旅游节</title>
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="format-detection" content="telephone=no">
	<meta name="full-screen" content="yes">
	<meta name="browsermode" content="application">
	<meta name="x5-orientation" content="portrait">
	<meta name="x5-fullscreen" content="true">
	<meta name="x5-page-mode" content="app">
	<meta name="format-detection" content="email=no">
	<meta name="msapplication-tap-highlight" content="no">
	<link rel="stylesheet" type="text/css" href="{$CDN_BASE_URL_RES}/html/css/zhuanti.css">
	<script src="{$CDN_BASE_URL_RES}/html/js/lib/require.js" data-main="{$CDN_BASE_URL_RES}/html/js/work/special.js?v=2.4.2"></script>
</head>
<body>
	<img src="{$CDN_BASE_URL_RES}/html/images/banner.jpg" class="img">
	<!-- 活动介绍 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t1.gif" class="img">
		<div class="font" id="list7">
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 精彩瞬间 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t2.gif" class="img">
		<div class="font">
			<ul class="list1" id="list1">

			</ul>
			<a href="javascript:;" class="more" date-url="wonderful">更多瞬间</a>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 文字报道 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t3.gif" class="img">
		<div class="font">
			<ul class="list2" id="list2">

			</ul>
			<a href="javascript:;" class="more" date-url="report">更多文字报道</a>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 视频报道 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t4.gif" class="img">
		<div class="font">
			<ul class="list2" id="list3">

			</ul>
			<a href="javascript:;" class="more" date-url="video">更多视频报道</a>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 名家专访 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t5.gif" class="img">
		<div class="font">
			<ul class="list1 list3" id="list4">

			</ul>
			<a href="javascript:;" class="more" date-url="celebrity">更多名家专访</a>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 活动背景 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t6.gif" class="img">
		<div class="font">
			<ul class="list2" id="list5">

			</ul>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<!-- 推荐商户 -->
	<div class="box">
		<img src="{$CDN_BASE_URL_RES}/html/images/t7.gif" class="img">
		<div class="font">
			<ul class="list1" id="list6">

			</ul>
			<a href="javascript:;" class="more" date-url="merchant">更多推荐商家</a>
		</div>
		<img src="{$CDN_BASE_URL_RES}/html/images/tb.gif" class="img">
	</div>
	<img src="{$CDN_BASE_URL_RES}/html/images/bottom.jpg" class="img" style="margin-top: 2rem;">


</body>
</html>