<!doctype html>
<html lang="zh">
<head>
{template public/WxShareJS}
	<meta charset="UTF-8">
	<title>作品集列表</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/wz/css/global.css">
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/wz/css/aui.css">
	<script src="{$CDN_BASE_URL_RES}/html/wz/js/setfontsize.js"></script>
	<script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
	<style>
		.zuopin{padding-top: 4%;}
		.more-btn{margin-top: 6%;margin-bottom: 6%;}
		.lucency-title li span{display: block;width: 3.1rem;height: 2.35rem;}
        .lucency-title li span img{width: 3.1rem;height: 2.35rem;object-fit: cover;-moz-object-fit: cover;-webkit-object-fit: cover;-o-object-fit: cover;-ms-object-fit: cover;}
        .lucency-title ul font{height: .5rem;overflow: hidden;white-space: nowrap;-ms-text-overflow: ellipsis;text-overflow: ellipsis;}
        .null{background-color: #fff;}
        .lucency-title ul font small {
            width: 1.5rem;
            height: .5rem;
            overflow: hidden;
            white-space: nowrap;
            -ms-text-overflow: ellipsis;
            display: inline-block;
            text-overflow: ellipsis;
            vertical-align: top;
            font-size: .28rem;
        }
	</style>
</head>
<body>
	<section class="container">
		<div class="aui-card-list  zuopin">
            <div class="lucency-title">
				<ul>
				</ul>
			</div>
        </div>
        <div class="more-btn"><span>加载更多</span></div>
	</section>
<script>
    var str_null = '<div class="null"><img src="{$CDN_BASE_URL_RES}/html/wz/images/null.jpg"><br><i>暂无发表作品</i></div>'; 
	function GetQueryString(name)  
	{
	     var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
	     var r = window.location.search.substr(1).match(reg);
	     if(r!=null)return  unescape(r[2]); return null;
	}
	console.log(GetQueryString("salesId"));
	var UID = GetQueryString("salesId");
    console.log(GetQueryString("gb_id"));
    var gb_id = GetQueryString("gb_id");

    var page = 1;
    var pageSize = 6;
    $(function () {
        getLists(page, pageSize);
    })

    //作品集列表
    function getLists(page, pageSize){
        $.ajax({
            type:"POST",
            url:"/mall/goods/item/boxGoods?salesId="+UID+'&page='+page+'&pageSize='+pageSize+'&gb_id='+gb_id,
            dataType:"json",
            cache: false,
            error: function(){
                alert("未知错误");
            },
            success: function(msg){
                if(msg.error_code == 0){
                    var win = msg.data[0].goodList;
                    console.log(win);
                    var str = '';
                        if(win==''){
                            $(".container").append(str_null);
                            $(".aui-btn").hide();
                        }
                        if(win.length<6){
                            $('.more-btn').hide();
                        }
                    $.each( win, function(index, content)
                    {
                        
                        str += '<li>';
                          str += '<a href="goodsInfo.html?id='+content.g_id+'">';
                            str += '<span><img src="'+content.image[0].gi_img+'!c400"></span>';
                            str += '<font><small>'+content.g_name+'</small>&nbsp;&nbsp;&nbsp;&nbsp; <i>¥'+content.g_price+'</i></font>';
                                // if(content.g_width==0||content.g_high==0){
                                //     str += '<h3>'+content.categoryName+' '+(content.itemAttr[0] && content.itemAttr[0].ga_key)+' '+(content.itemAttr[0] && content.itemAttr[0].ga_value)+'</h3>';
                                // }else{
                                //     str += '<h3>'+content.categoryName+' '+content.g_width+'cmx'+content.g_high+'cm</h3>';
                                // }
                          str += '</a>';
                        str += '</li>';
                        
                    });
                    if (page ==1){
                        $(".lucency-title ul").append(str);
                    }else {
                        $(".lucency-title ul").append(str);
                    }
                    page ++;
                    $('.more-btn').val(page);

                        
                }
            }
        });	
    }	

    //加载更多
    $(".more-btn").click(function(){
        getLists($('.more-btn').val(), pageSize);
    });
</script>
</body>
</html>