<!doctype html>
<html lang="zh">
<head>
{template public/WxShareJS}
	<meta charset="UTF-8">
	<title>作品列表</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/wz/css/global.css">
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/wz/css/aui.css">
	<script src="{$CDN_BASE_URL_RES}/html/wz/js/setfontsize.js"></script>
	<script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
	<style>
		.zuopin{padding-top: 4%;}
		.more-btn{margin-top: 6%;margin-bottom: 6%;}
		  .lucency-title li span{display: block;width: 3.1rem;height: 2.35rem;}
  .lucency-title li span img{width: 3.1rem;height: 2.35rem;object-fit: cover;
    -moz-object-fit: cover;
    -webkit-object-fit: cover;
    -o-object-fit: cover;
    -ms-object-fit: cover;}
    .lucency-title ul font{height: .5rem;overflow: hidden;white-space: nowrap;-ms-text-overflow: ellipsis;
    text-overflow: ellipsis;width: 94%;}
	</style>
</head>
<body>
	<section class="container">
		<div class="aui-card-list  zuopin">
            <div class="lucency-title">
				<ul>
					<!-- <li>
						<a href="">
							<span><img src="{$CDN_BASE_URL_RES}/html/wz/images/zuopin.jpg"></span>
							<font>水彩荷花&nbsp;&nbsp;&nbsp;&nbsp; <i>¥5800</i></font>
							<h3>国画 120x234cm</h3>
						</a>
					</li> -->
				</ul>
			</div>
        </div>
        <div class="more-btn"><span>加载更多</span></div>
	</section>
	<script>
	var str_null = '<div class="null"><img src="{$CDN_BASE_URL_RES}/html/wz/images/null.jpg"><br><i></i></div>'; 
	function GetQueryString(name)  
	{
	     var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
	     var r = window.location.search.substr(1).match(reg);
	     if(r!=null)return  unescape(r[2]); return null;
	}
	console.log(GetQueryString("uid"));
	var UID = GetQueryString("uid");

	var page = 1;
	var pageSize = 6;
    $(function () {
        getLists(page, pageSize);
    })
    //出售中作品
function getLists(page, pageSize){
    $.ajax({
        type:"POST",
        url:"/mall/goods/item/getNewGoodsList?salesId="+UID+'&page='+page+'&pageSize='+pageSize,
        dataType:"json",
        cache: false,
        error: function(){
            alert("未知错误");
        },
        success: function(msg){
            if(msg.error_code == 0){
                var win = msg.data.list;
                if(win.length > 0){
                    //console.log(win);
                    var str = '';
                    $.each( win, function(index, content)
                    {
                      if(content.count==0){
                        $(".shouzhong").append(str_null);
                        $(".null i").html("暂无发表作品");
                        $(".aui-btn").hide();
                      }else{
                        str += '<li>';
                          str += '<a href="goodsInfo.html?uid='+UID+'">';
                            str += '<span><img src="'+content.image[0].gi_img+'"></span>';
                            str += '<font>'+content.g_name+'&nbsp;&nbsp;&nbsp;&nbsp; <i>¥'+content.g_marketPrice+'</i></font>';
                            str += '<h3>'+content.categoryName+' '+content.image[0].gi_width+'cmx'+content.image[0].gi_height+'cm</h3>';
                          str += '</a>';
                        str += '</li>';
                      }
                      
                    });
                    //console.log(str);
                    if (page ==1){
                        $(".lucency-title ul").append(str);
                    }else {
                        $(".lucency-title ul").append(str);
                    }
                    page ++;

                    $('.more-btn').val(page);
                }
            }
        }
    });	
}	

        //加载更多
        $(".more-btn").click(function(){
            getLists($('.more-btn').val(), pageSize);
        });
	</script>
</body>
</html>