<!doctype html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<title>我的个人网站</title>
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/pcweb/css/global.css?18">
	<script src="https://libs.baidu.com/jquery/1.8.3/jquery.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/masonry-docs.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/web.js?25"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/pinyin.js"></script>
	<style>
		.quanzi-list .txt {
		    font-size: 14px;
		    line-height: 30px;
		    margin: 10px 0;
		}
		.null{
			background: #fff;
    border-radius: 6px;
    overflow: hidden;
    margin-bottom: 20px;
		}
		.quanzi div.quanzi-list div.suspend-info img{width: 15px;}
	</style>
</head>
<body>
	<div class="banner f-tac f-pr">
		<div class="container f-pa">
			<div class="hd-img"></div>
			<h3 class="name"></h3>
			<pre class="pinyin"></pre>
			<div class="region"></div>
			<div class="state">
				<ul>
					 
				</ul>
			</div>
			<img src="{$CDN_BASE_URL_RES}/html/pcweb/images/arrow.png">
		</div>
	</div>

	<div class="nav bgc">
		<div class="container f-tac">
			<ul>
				<li class="on"><a href="index.html?uid=">首页</a></li>
				<li><a href="profile.html?uid=">简介</a></li>
				<li><a href="works.html?uid=">作品</a></li>
				<li><a href="experience.html?uid=">获奖经历</a></li>
				<li><a href="circle.html?uid=">我的圈子</a></li>
			</ul>
		</div>
	</div>

	<div class="container layoyt clearfix index index0">
		<div class="f-fl" style="margin-top: -10px;">
			<div id="masonry" class="container-fluid demo works1">
				<ul class="clearfix">
					 
				</ul> 
			</div>			
		</div>
		<div class="sidebar f-fr">
			<div class=" jianjie mb20 bgc border-radius-6" >
				<div class="titlebar clearfix"><h3 class="">简介<em>ABOUT ME</em></h3></div>
				<div class="JIANJIE">
					 
				</div>
				<div class="more-btn"><i>查看更多</i><img src="{$CDN_BASE_URL_RES}/html/pcweb/images/arrow.png"></div>
			</div>
			<div class="jianjie mb20 bgc border-radius-6 jingli">
				<div class="titlebar clearfix"><h3 class="">获奖经历<em>HONOR</em></h3></div>
				<div class="HJJL">
					<ul>
			             
			        </ul> 
		        </div>
			</div>
			<div class=" jianjie mb20 bgc border-radius-6 quanzi01 quanzi QUANZI1">
				<div class="titlebar clearfix"><h3 class="">我的圈子<em>CIRCLE</em></h3></div>
				<!-- <div class="quanzi-list">
				    <div class="suspend clearfix">
				        <div class="photo-box">
				            <span href="javasrcipt:vodi(0);" class="photo">
				                <img src="https://cdn.16988.cn/attach/avatar/ef/9c/ef9c93e160ef397f617859d6385bf947.jpg"></span>
				        </div>
				        <div class="suspend-info">
				            <h3>欢乐颂</h3>
				            <p>2天前</p>
				        </div>
				    </div>
				    <p class="txt">多寿图</p>
				    <div class="quanzi-pic demo">
				        <ol class="clearfix">
				            <li><img src="https://cdn.16988.cn/attach/treasure/31/28/31289219c8902ad74476377a1ec06844.png"></li>
				            <li><img src="https://cdn.16988.cn/attach/treasure/31/28/31289219c8902ad74476377a1ec06844.png"></li>
				            <li><img src="{$CDN_BASE_URL_RES}/html/pcweb/images/l1.jpg"></li>
				        </ol>
				    </div>
				</div>	 -->
			</div>
		</div>
	</div>
	<div class="photo-mask"></div>
	<div class="photo-panel">
	    <div class="photo-div">
	        <div class="photo-left">
	            <div class="arrow-prv"></div>
	        </div>
	        <div class="photo-img">
	            <div class="photo-bar">
	                <div class="photo-close"></div>
	            </div>
	            <div class="photo-view-h">
	                <img src="" />
	            </div>
	        </div>
	        <div class="photo-right">
	            <div class="arrow-next"></div>
	        </div>
	    </div>
	</div>

</body>
</html>