<!doctype html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<title>我的个人作品</title>
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/pcweb/css/global.css?6">
	<script src="https://libs.baidu.com/jquery/1.8.3/jquery.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/masonry-docs.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/web.js?180110"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pcweb/js/pinyin.js"></script>
		<script>
        $(window).on('load',function(){
            $(window).scrollTop(640);
            console.log($(window).scrollTop())
        }); 
	</script>
	<style>
		.null{
			background: #fff;
    border-radius: 6px;
    overflow: hidden;
    margin-bottom: 20px;
		}
		.box img{height: 320px;    object-fit: cover;
    -moz-object-fit: cover;
    -webkit-object-fit: cover;
    -o-object-fit: cover;
    -ms-object-fit: cover;}
    .index .f-fl #masonry2 .box img{border-radius: 6px 6px 0 0;}
	</style>

</head>
<body>
	<div class="banner f-tac f-pr">
		<div class="container f-pa">
			<div class="hd-img"></div>
			<h3 class="name"></h3>
			<pre class="pinyin"></pre>
			<div class="region"></div>
			<div class="state">
				<ul>
					 
				</ul>
			</div>
			<img src="{$CDN_BASE_URL_RES}/html/pcweb/images/arrow.png">
		</div>
	</div>
	<div class="nav bgc">
		<div class="container f-tac">
			<ul>
				<li><a href="index.html?uid=">首页</a></li>
				<li><a href="profile.html?uid=">简介</a></li>
				<li class="on"><a href="works.html?uid=">作品</a></li>
				<li><a href="experience.html?uid=">获奖经历</a></li>
				<li><a href="circle.html?uid=">我的圈子</a></li>
			</ul>
		</div>
	</div>
	<div class="container layoyt clearfix index index02">
		<div class="f-fl" style="width: 1200px;">
			<div id="masonry2" class="container-fluid demo works2">
				<ul></ul>
			</div>			
		</div>
	</div>
		<div class="f-tac btn more-works border-radius-6">加载更多作品</div>
	<div class="photo-mask"></div>
	<div class="photo-panel">
	    <div class="photo-div">
	        <div class="photo-left">
	            <div class="arrow-prv"></div>
	        </div>
	        <div class="photo-img">
	            <div class="photo-bar">
	                <div class="photo-close"></div>
	            </div>
	            <div class="photo-view-h">
	                <img src="" />
	            </div>
	        </div>
	        <div class="photo-right">
	            <div class="arrow-next"></div>
	        </div>
	    </div>
	</div>

</body>
</html>