<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>近期活动</title>
    <link rel="stylesheet" href="https://cdn.16988.cn/res/html/css/global.css?171116">
    <script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
    <script src="https://cdn.16988.cn/res/html/js/setfontsize.js"></script>
</head>
<style>
    .tab-wrap{
        height: 40px;
        margin-top: 10px;
    }
    .tab {
        display: flex;
        text-align: center;
        font-size: 14px;
    }

    .tab li {
        flex: 1;
        list-style: none;
        position: relative;
    }

    .tab span {
        color: #939393;
    }

    .tab .tabactive {
        color: #333;
    }

    .tab .tabactive::after {
        display: inline-block;
        content: '';
        border-top: 2px solid #D7AB73;
        width: 33px;
        margin: 0 auto;
        position: absolute;
        bottom: -8px;
        left: 0;
        right: 0;
    }
    body {
        background: #f6f6f6;
        overflow-x: hidden;
    }

    .active-img {
        width: 100%;
    }

    img {
        width: 100%;
    }

    .active-word {
        background: #fff;
        padding: 15px;
        font-size: 14px;
        margin-bottom: 10px;
    }

    .state {
        padding: 4px 15px;
        float: right;
    }

    .over {
        background: #EDEDED;
        color: #939393;
        border-radius: 20px;
        margin-top: -25px;
    }

    .active {
        background: #cea068;
        color: #fff;
    }

    .active-title {
        vertical-align: -webkit-baseline-middle;
        /* display: inline-block; */
        width: 3rem;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        color: #1E1E1E;
        margin-bottom: 15px;
    }
    .active-time{
        color:#7E7E7E;
        font-size:11px;
    }
</style>

<body>
    <div class="tab-wrap">
        <ul class="tab">
            <li class="active-ing"><span class="tabactive">进行中</span></li>
            <li class="active-end"><span>已结束</span></li>
        </ul>
    </div>
    <div >
        <div class="active-list">

        </div>
    </div>

</body>
<script>
    function getdate() {
        var now = new Date(),
            y = now.getFullYear(),
            m = now.getMonth() + 1,
            d = now.getDate();
        return y + "-" + (m < 10 ? "0" + m : m) + "-" + (d < 10 ? "0" + d : d) + " " + now.toTimeString().substr(0, 8);
    }
    function getlist(istype){
        $.ajax({
            type: "POST",
            url: "/mall/activity/activity/lists?page=1&pageSize=20&isActive="+istype,
            dataType: "json",
            cache: false,
            
        error: function () {
            alert("未知错误");
        },
        success: function (msg) {
            if (msg.error_code == 0) {
                var activeData = msg.data.list;
                if (activeData.length > 0) {
                    console.log(activeData);
                    $.each(activeData, function (index, content) {
                        var deadline = content.activity_end_date;
                        console.log(deadline);
                        var nowDate = new Date().valueOf();
                        console.log(getdate(nowDate));
                        // var nowDate = new Date(nowDate).toLocaleDateString().replace(/\//g, "-") + " " + new Date(nowDate).toTimeString().substr(0, 8);
                        var nowDate = getdate(nowDate);
                        if (deadline < nowDate) {
                            str_state = '<span class="over state">已结束</span>'
                        } else {
                            // str_state = '<span class="active state"></span>'
                            str_state = ''
                        }
                        str = '<div class="active-img">\
                        <a href="/html/apph5/scheme.html?aid='+ content.activity_id + '">\
                        <img onerror="imgExists(this)" src='+ content.activity_banner + '></a>\
                        </div>\
                        <div class="active-word">\
                        <p class="active-title">'+ content.activity_title + '</p>\
                        '+ str_state + '\
                        <p class="active-time">'+ content.activity_end_date.substr(5,11) + '</p>\
                        </div>'
                        $(".active-list").empty();
                        $(".active-list").append(str);
                    });
                }
            } else {
                alert(msg.error_msg);
            };
        }
        })
    }
    getlist(1)
    // 
    function imgExists(e) {
        //默认图片
        var imgUrl = "//cdn.16988.cn/res/html/images/h5/zw.png";
        var img = new Image();
        img.src = imgUrl;
        img.style.width = "100px";
        img.style.margin = "0 auto";
        //判断图片大小是否大于0 或者 图片高度与宽度都大于0
        if (img.filesize > 0 || (img.width > 0 && img.height > 0)) {
            e.src = imgUrl;

        } else {
            return false
        }
    }
    $(".active-ing").click(function(){
        $(this).find('span').addClass('tabactive');
        $(".active-end").find('span').removeClass('tabactive');
        getlist(1)
    })
    $(".active-end").click(function(){
        $(this).find('span').addClass('tabactive');
        $(".active-ing").find('span').removeClass('tabactive');
        getlist(-1)
    })
</script>

</html>

