<!DOCTYPE html>
<html lang="en">

<head>
{template public/WxShareJS}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1.00001,maximum-scale=1.00001,user-scalable=no,minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>匠人优选申请</title>
    <link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/css/global.css?171116">
</head>
<style>
    body {
        font-size: 14px;
        background: #f6f6f6;
        overflow-x: hidden;
    }

    input {
        border: none;
        float: right;
        text-align:right;
    }

    input::-webkit-input-placeholder {
        text-align: right;
    }

    .form {
        background: #fff;
        padding: 15px;
    }

    textarea {
        border: none;
        background: #f4f4f4;
        padding: 10px;
        width: 100%;
        margin-top: 10px;
    }

    .form-common {
        margin: 10px 0;
        padding: 10px 0;
    }

    .border {
        border-bottom: 1px solid #f8f8f8;
    }

    .portfolio {
        display: inline-block;
    }

    img {
        width: 100%;
    }

    .img-list {
        display: inline-block;
        /* width: 80px;
        height: 80px; */
        /* background-image: url({$CDN_BASE_URL_RES}/html/images/h5/banner.png);
        background-repeat: no-repeat;
        background-size: cover; */
    }
.img-list li{
    width: 60px;
    height:60px;
    background-repeat: no-repeat;
    background-size: cover;
    float: left;
}
    .file-btn {
        display: inline-block;
        width: 80px;
        height: 80px;
    }

    .submit-btn {
        text-align: center;
        margin-top: 30px;
        margin-bottom:20px;
    }

    .submit-btn button {
        background: #d1a570;
        padding: 15px;
        width: 70%;
        border-radius: 5px;
        color: #fff;
        margin-top: 20px;
        font-size: 18px;
    }
    .mask{
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.3);
        display: none;
    }
    .alert{
        background: #fff;
        text-align: center;
        color: #d1a570;
        width: 70%;
        margin: 0 auto;
        margin-top: 50%;
        padding: 30px;
    }
    .close-tip{
        background: #d1a570;
        padding: 15px;
        width: 85%;
        border-radius: 5px;
        color: #fff;
        margin-top: 20px;
    }
    /* .pic-list{display: inline-block;font-size:0;} */
    .upload-img{
        display:inline-block;
        width:80px;
        height:80px;
        overflow: hidden;
        margin: 2px 5px 2px 0;
        position: relative;
    }
    .pic-list img{width: 100%;float:left;}
    .limit-img-tip{
        width: 160px;
        margin: 0 auto;
        background: #000;
        color: #fff;
        text-align: center;
        border-radius: 5px;
        padding: 5px;
        position: absolute;
        left: 50%;
        margin-left: -80px;
        margin-top: -280px;
        display:none;
    }
.close-mask{
    position: absolute;
    right: 0;
    top: 0;
    background: rgba(0,0,0,0.03);
    bottom:  0;
    left: 0;
}
.close-mask .close-img{
    width: 20px;
    float:  right;
    margin-right: 2px;
    margin-top: 2px;
}
</style>

<body>
    <form >
        <div class="form">
            <div class="form-common border">
                <span>姓名</span>
                <input type="text" placeholder="请输入您的姓名" name="sign_name" id="sign_name">
            </div>
            <div class="form-common border">
                <span>联系方式</span>
                <input type="text" placeholder="请输入您的手机号" name="sign_phone" id="sign_phone">
            </div>
            <div class="form-common border">
                <span>作品类别</span>
                <input type="text" placeholder="如：国画、瓷器" name="sign_industry" id="sign_industry">
            </div>
            <div class="form-common">
                <p>个人简介</p>
                <textarea name="sign_info" cols="30" rows="5" placeholder="提示：请填写您的个人简介" id="sign_info"></textarea>
            </div>
            <div class="form-common">
                <p style="margin-bottom: 10px;">代表作品</p>
                <!-- <div class="portfolio">
                    <img src="" alt=""> 
                    <span class="pro-img"></span> 
                    <ul class="img-list"></ul> 
                </div> -->
                <!-- <ul class="img-list"></ul> -->
                <span class="pic-list">
                   
                </span> 
                <label class="file-btn" for="xFile" id="upload">
                    <img  src="{$CDN_BASE_URL_RES}/html/images/h5/btn_03.png?v=1">
                </label>
                <input class="" type="file" name="sign_image" id="xFile" style="position:absolute;clip:rect(0 0 0 0);" accept="image/*" >
            </div>
            <div style="margin-left:10px;margin-top:-10px;">
                <p>提示：最多上传5张</p>
            </div>
        </div>
        <div class="submit-btn">
            <p>提交申请后，工作人员会在24小时内和你联系</p>
            <button>提交资料</button>
        </div>

    </form>
    <div class="mask">
        <div class="alert">
            <h2>提交成功</h2>
            <p>工作人员会在24小时内和你联系,请你耐心等待</p>
            <button class="close-tip">知道了</button>
        </div>
    </div>
    <div class="limit-img-tip">最多只可上传5张图片</div>
    <script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
    <script src="{$CDN_BASE_URL_RES}/html/js/setfontsize.js"></script>
</body>
<script>
 var filechooser = document.getElementById("xFile");
  //    用于压缩图片的canvas
  var canvas = document.createElement("canvas");
  var ctx = canvas.getContext('2d');
  //    瓦片canvas
  var tCanvas = document.createElement("canvas");
  var tctx = tCanvas.getContext("2d");
  var maxsize = 100 * 1024;
  var sign_works = {};
  $("#filechooser").on("click", function() {
        // filechooser.click();
      })
      .on("touchstart", function() {
        $(this).addClass("touch")
      })
      .on("touchend", function() {
        $(this).removeClass("touch")
      });
  filechooser.onchange = function() {
    if (!this.files.length) return;
    var files = Array.prototype.slice.call(this.files);
    console.log(files.length)
    if (files.length > 5) {
    //   alert("最多同时只可上传5张图片");
        
      return;
    }
    
    files.forEach(function(file, i) {
      if (!/\/(?:jpeg|png|gif)/i.test(file.type)) return;
      var reader = new FileReader();
      var li = document.createElement("li");
//          获取图片大小
      var size = file.size / 1024 > 1024 ? (~~(10 * file.size / 1024 / 1024)) / 10 + "MB" : ~~(file.size / 1024) + "KB";
    //   li.innerHTML = '<div class="progress"><span></span></div><div class="size">' + size + '</div>';
    console.log($(".pic-list").children().length)
        if($(".pic-list").children().length>4){
            $(".limit-img-tip").show();
                setTimeout(() => {
                    $(".limit-img-tip").hide();
                }, 1500);
            return;
        }

      $(".img-list").append($(li));
      reader.onload = function() {
        var result = this.result;
        var img = new Image();
        img.src = result;
        $(li).css("background-image", "url(" + result + ")");
        //如果图片大小小于100kb，则直接上传
        if (result.length <= maxsize) {
          img = null;
          upload(result, file.type, $(li));
          return;
        }
//      图片加载完毕之后进行压缩，然后上传
        if (img.complete) {
          callback();
        } else {
          img.onload = callback;
        }
        function callback() {
          var data = compress(img);
          upload(data, file.type, $(li));
          img = null;
        }
      };
      reader.readAsDataURL(file);
    })
  };
  //    使用canvas对大图片进行压缩
  function compress(img) {
    var initSize = img.src.length;
    var width = img.width;
    var height = img.height;
    //如果图片大于四百万像素，计算压缩比并将大小压至400万以下
    var ratio;
    if ((ratio = width * height / 4000000) > 1) {
      ratio = Math.sqrt(ratio);
      width /= ratio;
      height /= ratio;
    } else {
      ratio = 1;
    }
    canvas.width = width;
    canvas.height = height;
//        铺底色
    ctx.fillStyle = "#fff";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    //如果图片像素大于100万则使用瓦片绘制
    var count;
    if ((count = width * height / 1000000) > 1) {
      count = ~~(Math.sqrt(count) + 1); //计算要分成多少块瓦片
//            计算每块瓦片的宽和高
      var nw = ~~(width / count);
      var nh = ~~(height / count);
      tCanvas.width = nw;
      tCanvas.height = nh;
      for (var i = 0; i < count; i++) {
        for (var j = 0; j < count; j++) {
          tctx.drawImage(img, i * nw * ratio, j * nh * ratio, nw * ratio, nh * ratio, 0, 0, nw, nh);
          ctx.drawImage(tCanvas, i * nw, j * nh, nw, nh);
        }
      }
    } else {
      ctx.drawImage(img, 0, 0, width, height);
    }
    //进行最小压缩
    var ndata = canvas.toDataURL('image/jpeg', 0.1);
    console.log('压缩前：' + initSize);
    console.log('压缩后：' + ndata.length);
    console.log('压缩率：' + ~~(100 * (initSize - ndata.length) / initSize) + "%");
    tCanvas.width = tCanvas.height = canvas.width = canvas.height = 0;
    return ndata;
  }
  //    图片上传，将base64的图片转成二进制对象，塞进formdata上传
  function upload(basestr, type, $li) {
    var text = window.atob(basestr.split(",")[1]);
    var buffer = new Uint8Array(text.length);
    var pecent = 0, loop = null;
    for (var i = 0; i < text.length; i++) {
      buffer[i] = text.charCodeAt(i);
    }
    var blob = getBlob([buffer], type);
    var xhr = new XMLHttpRequest();
    var formdata = getFormData();
    formdata.append('imagefile', blob);
    xhr.open('post', '/user/common/uploadSignImages');
    xhr.onreadystatechange = function() {
      if (xhr.readyState == 4 && xhr.status == 200) {
        console.log(xhr.responseText)
        var jsonData = JSON.parse(xhr.responseText);
        var imagedata = jsonData.data[0] || {};
        console.log(jsonData.data[0])
        var text = imagedata.previewUrl ? '上传成功' : '上传失败';
        console.log(text + '：' + imagedata.previewUrl);
        clearInterval(loop);
        //当收到该消息时上传完毕
        $li.find(".progress span").animate({'width': "100%"}, pecent < 95 ? 200 : 0, function() {
          $(this).html(text);
        });
        if (!imagedata.previewUrl) return;
        $(".pic-list").append('<div class="upload-img"><div class="close-mask"><img class="close-img" src="{$CDN_BASE_URL_RES}/html/images/h5/close-btn.png"></div><img src="' + imagedata.previewUrl + '"  class="imgsrc"/></div>');
        // 删除图片
        $(".close-mask").click(function(){
            console.log("删除图片")
            $(this).parent().remove()
        })
      }
    };
    
    //数据发送进度，前50%展示该进度
    xhr.upload.addEventListener('progress', function(e) {
      if (loop) return;
      pecent = ~~(100 * e.loaded / e.total) / 2;
      $li.find(".progress span").css('width', pecent + "%");
      if (pecent == 50) {
        mockProgress();
      }
    }, false);
    //数据后50%用模拟进度
    function mockProgress() {
      if (loop) return;
      loop = setInterval(function() {
        pecent++;
        $li.find(".progress span").css('width', pecent + "%");
        if (pecent == 99) {
          clearInterval(loop);
        }
      }, 100)
    }
    xhr.send(formdata);
  }
  /**
   * 获取blob对象的兼容性写法
   * @param buffer
   * @param format
   * @returns {*}
   */
  function getBlob(buffer, format) {
    try {
      return new Blob(buffer, {type: format});
    } catch (e) {
      var bb = new (window.BlobBuilder || window.WebKitBlobBuilder || window.MSBlobBuilder);
      buffer.forEach(function(buf) {
        bb.append(buf);
      });
      return bb.getBlob(format);
    }
  }
  /**
   * 获取formdata
   */
  function getFormData() {
    var isNeedShim = ~navigator.userAgent.indexOf('Android')
        && ~navigator.vendor.indexOf('Google')
        && !~navigator.userAgent.indexOf('Chrome')
        && navigator.userAgent.match(/AppleWebKit\/(\d+)/).pop() <= 534;
    return isNeedShim ? new FormDataShim() : new FormData()
  }
  /**
   * formdata 补丁, 给不支持formdata上传blob的android机打补丁
   * @constructor
   */
  function FormDataShim() {
    console.warn('using formdata shim');
    var o = this,
        parts = [],
        boundary = Array(21).join('-') + (+new Date() * (1e16 * Math.random())).toString(36),
        oldSend = XMLHttpRequest.prototype.send;
    this.append = function(name, value, filename) {
      parts.push('--' + boundary + '\r\nContent-Disposition: form-data; name="' + name + '"');
      if (value instanceof Blob) {
        parts.push('; filename="' + (filename || 'blob') + '"\r\nContent-Type: ' + value.type + '\r\n\r\n');
        parts.push(value);
      }
      else {
        parts.push('\r\n\r\n' + value);
      }
      parts.push('\r\n');
    };
    // Override XHR send()
    XMLHttpRequest.prototype.send = function(val) {
      var fr,
          data,
          oXHR = this;
      if (val === o) {
        // Append the final boundary string
        parts.push('--' + boundary + '--\r\n');
        // Create the blob
        data = getBlob(parts);
        // Set up and read the blob into an array to be sent
        fr = new FileReader();
        fr.onload = function() {
          oldSend.call(oXHR, fr.result);
        };
        fr.onerror = function(err) {
          throw err;
        };
        fr.readAsArrayBuffer(data);
        // Set the multipart content type and boudary
        this.setRequestHeader('Content-Type', 'multipart/form-data; boundary=' + boundary);
        XMLHttpRequest.prototype.send = oldSend;
      }
      else {
        oldSend.call(this, val);
      }
    };
  }
// 提交资料
var sign_img = $(".imgsrc");
console.log(sign_img.length)
if(sign_img.length < 5){
    $(".submit-btn button").click(function (event) {
            event.preventDefault();
            var sign_name = $("#sign_name").val();
            var sign_industry = $("#sign_industry").val();
            var sign_info = $("#sign_info").val();
            var sign_phone = $("#sign_phone").val();
            var sign_img = $(".imgsrc");
            var sign_works = {};
            var sign_works_ = {};
            for(var i = 0;i<sign_img.length;i++){
                sign_works[i] = sign_img[i].src;
            }
            console.log(sign_works)
            var sign_works_str = JSON.stringify(sign_works)
            // var uId = $.getUrlParam('uid');
            console.log(sign_name)
            if (sign_name == ''&&'undefined') {
                alert("请输入姓名");
                return false;
            }
            regmobile = /^1[0-9]\d{9}$/;
            if (!regmobile.test(sign_phone)) {
                alert('请正确填写手机号码');
                return false;
            }
            if (sign_industry == ''&&'undefined') {
                alert("请输入作品类别");
                return false;
            }
            if (sign_info == ''&&'undefined') {
                alert("请输入个人简介");
                return false;
            }
            
            $.ajax({
                type: "POST",
                url: "/user/common/userSign?sign_name=" + sign_name + "&sign_industry=" + sign_industry + "&sign_info="+sign_info+"&sign_phone="+sign_phone+"&sign_works="+sign_works_str,
                dataType: "json",
                cache: false,
                error: function () {
                    alert("未知错误");
                },
                success: function (msg) {
                    console.log(msg);
                    $(".mask").show()
                }
            });
        });
        $(".close-tip").click(function(){
            $(".mask").hide();
            window.location.href='/html/apph5/artist-intro.html';
        })
        
}

</script>
<script>
  window.onload = function(){
        // 删除图片
        $(".close-mask").click(function(){
            console.log("删除图片")
            $(this).parent().remove()
        })
    }  
</script>
</html>