<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>拍品发布须知</title>
</head>
<style lang="css">
    *{
        padding: 0;
        margin: 0;
    }
    body{
        padding: 15px;
    }
    h1{
        font-size: 16px;
        margin-bottom:25px; 
    }
    h2{
        margin-top: 25px;
        font-size: 16px;
    }
    p{
        color: #1E1E1E;
        font-size: 12px;
        margin: 10px 0;
        line-height: 1.8;
    }
</style>
<body>
    <h1>
        掌玩拍品发布须知
    </h1>
    <p>
        1.本人为发布人本人并且承诺对本次发布拍品及拍品交易愿意承担全部相关法律责任，出现违法违规发布行为的一切后果由发布人本人承担。
    </p>
    <p>
        2.发布人本人已充分知悉国家关于禁止各类违禁物品销售和交易的规定，尤其是关于禁止违法出售、收购、利用野生动物及其相关制品发布广告或相关信息等规定。
    </p>
    <p>
        3.发布人对于以上平台拍品发布须知内容已充分知悉并愿意遵照执行。
    </p>
    <h2>
        积分规则的最终解释权归掌玩所有
    </h2>
</body>
</html>