<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta name="format-detection" content="email=no">
  <title></title>
   <!-- CSS引用 -->
  <link rel="stylesheet" href="{$DOMAIN_APP}/res/html/biArtifact/index.min.css?v=2" type="text/css"/>
  <!-- JS引用 -->
  <script type="text/javascript" src="https://s29.9956.cn/res/crowdsource/lib/vue.min.js?v=1"></script>
  <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
  <script type="text/javascript">
    //静态资源设置路径
    window.resourceBaseUrl = '{$DOMAIN_APP}/res/html/';
  </script>
  <!-- <script type="text/javascript" src="http://s29.9956.cn/res/crowdsource/lib/vue.min.js"></script> -->
  </head>
  <body style="background: #fff;overflow-x: hidden;">
    <div id="app"></div>
    <script type="text/javascript" src="{$DOMAIN_APP}/res/html/biArtifact/index.min.js?v=1"></script>
    <script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/baidu_stat.js"></script>
    <!-- built files will be auto injected -->
  </body>
  <style>
  
  </style>
</html>
