<!DOCTYPE html>
<html lang="en">
<head>
{template public/WxShareJS}
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta name="format-detection" content="email=no">
  <title>掌门人课堂</title>

  <!-- <link rel="stylesheet" href="http://dev-cdn.zhangwan.shop/res/html/bossLesson/index.min.css?v=8" type="text/css"/> -->
  <!-- <link rel="stylesheet" href="https://app.16988.cn/res/html/bossLesson/index.min.css" type="text/css"/> -->
  <link rel="stylesheet" href="https://app.16988.cn/res/html/bossLesson/index.min.css?v=10" type="text/css"/>
  <script type="text/javascript" src="https://s29.9956.cn/res/crowdsource/lib/vue.min.js"></script>
  <script type="text/javascript">
    //静态资源设置路径
    // window.resourceBaseUrl = 'http://dev-cdn.zhangwan.shop/res/html/'; //测试环境路径
    //   window.resourceBaseUrl = 'https://cdn.16988.cn/res/html/'; //线上环境路径
    //  window.resourceBaseUrl = 'https://app.16988.cn/res/html/';
    window.resourceBaseUrl = 'https://app.16988.cn/res/html/';
    
  </script>
  </head>
  <body style="overflow-x: hidden;">
    <div id="app"></div>
    <!-- <script type="text/javascript" src="http://dev-cdn.zhangwan.shop/res/html/bossLesson/index.min.js?v=8"></script> -->
    <!-- <script type="text/javascript" src="https://app.16988.cn/res/html/bossLesson/index.min.js?v=16"></script> -->
    <script type="text/javascript" src="https://app.16988.cn/res/html/bossLesson/index.min.js?v=16"></script>    
  </body>
</html>
