<!DOCTYPE html>
<html lang="zh-CN" style="overflow-x: hidden;">
<head>
{template public/WxShareJS}
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta name="format-detection" content="email=no">
  <title>掌玩杯艺术大赛</title>
  <!-- CSS引用 -->
  <link rel="stylesheet" href="{$DOMAIN_APP}/res/html/artCompete/index.min.css?v=2" type="text/css"/>
  <script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
  <!-- JS引用 -->
  <script type="text/javascript" src="https://s29.9956.cn/res/crowdsource/lib/vue.min.js?v=17"></script>
  <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
  <script type="text/javascript">
    //静态资源设置路径
    window.resourceBaseUrl = '{$DOMAIN_APP}/res/html/';
  </script>
  </head>
  <body style="overflow-x: hidden;">
    <div id="app"></div>
    <script type="text/javascript" src="{$DOMAIN_APP}/res/html/artCompete/index.min.js?v=2"></script>
    <script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/baidu_stat.js"></script>
  </body>
  <style>
</style>
</html>