<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden;">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta name="format-detection" content="email=no">
  <title></title>
  <style>
    html,body{
      -webkit-overflow-scrolling:touch;
      overflow-x: hidden;
    }
  </style>
  <!-- CSS引用 -->
  <link rel="stylesheet" href="{$DOMAIN_APP}/res/html/exhiBition/index.min.css?v=5" type="text/css"/>
  <!-- <script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script> -->
  <!-- JS引用 -->
  <script type="text/javascript" src="https://cdn.16988.cn/res/html/js/lib/vue/vue.min.js"></script>
  <!-- <script src="https://cdn.bootcss.com/vue/2.5.0/vue.js"></script> -->
  <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
  <script type="text/javascript" src="https://b.bdstatic.com/searchbox/icms/searchbox/js/swan-2.0.1.js"></script>
  <script type="text/javascript">
    //静态资源设置路径
    window.resourceBaseUrl = '{$DOMAIN_APP}/res/html/';
  </script>
  </head>
  <body style="overflow-x: hidden;">
    <div id="app"></div>
    <script type="text/javascript" src="{$DOMAIN_APP}/res/html/exhiBition/index.min.js?v=26"></script>
    <script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/baidu_stat.js"></script>
   
  </body>
 
</html>
