<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" style="overflow-x: hidden;">
<head>
{template public/WxShareJS}
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width">
  <meta name="format-detection" content="telephone=no">
  <meta name="format-detection" content="email=no">
  <title>少儿书法大赛</title>
  <!-- CSS引用 -->
  <link rel="stylesheet" href="{$DOMAIN_APP}/res/html/handWriting/index.min.css?v=21" type="text/css"/>
  <script src="https://s28.9956.cn/static/v3_1/js/jquery.min.js"></script>
  <!-- JS引用 -->
  <script type="text/javascript" src="https://s29.9956.cn/res/crowdsource/lib/vue.min.js?v=17"></script>
  <!-- <script src="https://cdn.bootcss.com/vue/2.5.0/vue.js"></script> -->
  <script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
  <script type="text/javascript">
    //静态资源设置路径
    window.resourceBaseUrl = '{$DOMAIN_APP}/res/html/';
  </script>
  </head>
  <body style="overflow-x: hidden;">
    <div id="app"></div>
    <script type="text/javascript" src="{$DOMAIN_APP}/res/html/handWriting/index.min.js?v=21"></script>
    <script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/baidu_stat.js"></script>
    <!-- <div class="back-top" >
            <img src="{$CDN_BASE_URL_RES}/html/images/h5/top@2x.png" alt="">
        </div> -->
  </body>
  <style>
  html,body{
    height: 100%;
    -webkit-overflow-scrolling:touch;
  }
  /* // 返回顶部 */
/* .back-top {
  position: fixed;
  width: 40px;
  right: 15px;
  bottom: 100px;
  z-index: 3;
} */
</style>
<script>
  // $(function(){
  //   $(window).scroll(function(){
  //     if($(window).scrollTop()>10){
  //       $(".back-top").css("display","block");
  //     }else{
  //        $(".back-top").css("display","none");
  //     }
  //   });
  //   $(".back-top").click(function(){
  //     $("html,body").animate({scrollTop:0},300)
  //     // $(".back-top img").css("display","none");
  //   });
  // });
  </script>
</html>
