<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>消息</title>
</head>
<style>
    #jump-btn{
        text-align: center;
        padding-top: 150px;
    }
    #jump-btn span{
        background: #000;
        padding: 15px 30px;
        border-radius: 5px;
        color: #fff;
    }
</style>
<body>
    <div id="jump-btn" >
        <!-- <span >到代金券查看</span> -->
    </div>
</body>
<script>
    // 获取URL
    function getURL(name){
        var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
        var r = window.location.search.substr(1).match(reg);
        if (r != null) return unescape(r[2]); return null;
    }
    if (typeof HandPlay != "undefined") {
        //在掌玩中
        if(getURL('targetPage') == 'couponList'){
            HandPlay.execNative('{"targetPage":"couponList"}'); //跳转代金券页面
            HandPlay.closeCurrentPage()
        }else{
            HandPlay.execNative('{"targetPage":"treasure"}');//去寻宝
        }
    } else {
        //不在掌玩中
    }
</script>
</html>