<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>用户等级规则及权益</title>
</head>
<style lang="css">
    * {
        padding: 0;
        margin: 0;
        font-size: 12px;
    }

    body {
        padding: 15px;
    }

    p {
        color: #1E1E1E;
        font-size: 12px;
        line-height: 20px;
    }

    h2 {
        font-size: 15px;
        padding-bottom: 25px;
        padding-top: 10px;
    }

    .level {
        padding: 15px 0;
        line-height: 20px;
    }

    ul {
        list-style: none;
        display: flex;

    }

    ul li {
        /*flex: 1;*/
    }
    .widfi{
        width: 36%;
    }
    ul .wid{
        width: 10%;
    }
</style>

<body>
    <h2>如何等级升级？</h2>
    <p>单个等级只能认证一次；每通过一次认证增加星数1星；积分增
        加参见【招财秘笈】；会员特权及专属特权具体参见掌玩APP系
        统通知及公示页面</p>
    <div class="level">
        <ul>
            <li class="widfi">未实名用户：</li>
            <li class="wid">V0</li>
            <li class="wid">0星</li>
        </ul>
        <ul>
            <li class="widfi">实名认证用户：</li>
            <li class="wid">V1</li>
            <li class="wid">1星</li>
        </ul>
        <ul>
            <li class="widfi">认证艺术家用户：</li>
            <li class="wid">V2</li>
            <li class="wid">2星</li>
        </ul>
        <ul>
            <li class="widfi">签约艺术家用户：</li>
            <li class="wid">V3</li>
            <li class="wid">3星</li>
        </ul>
    </div>
    <p>
        <strong>买家：</strong>
        消费金额越高，买家星级越高；每天领取的优惠券张数
        及积分任务奖励就越高；具体以掌玩APP系统通知及公示页面为
        准（目前默认注册用户均为V0,实名认证的买家为V1）
    </p>
    <p>
        <strong>卖家：</strong>
        销售收入金额及认证等级越高，卖家星级越高；每天可发
        布的商品数、商家特色专属权限数、平台专属客服数及积分任务
        奖励就越高；

    </p>
    <h2>积分规则的最终解释权归掌玩所有</h2>
</body>

</html>