
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
{template public/WxShareJS}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>大转盘活动</title>

<link href="{$CDN_BASE_URL_RES}/html/css/lottery.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/jquery-1.10.2.js"></script>
<script type="text/javascript" src="{$CDN_BASE_URL_RES}/html/js/awardRotate.js"></script>


</head>
<style>
  /* a{
    overflow: hidden !important;
  } */
  .lottry{
    /* display: none; */
    width: 50%;
    margin: 0 auto;
    margin-top: 65%;
  }
  img{
    width: 100%;
  }
  .close{
    position: absolute;
    top: 140px;
    right: 66px;
    width: 40px;
  }
</style>
<body style="background:#c00;overflow-x:hidden !important;color:#fff;">
    <img src="{$CDN_BASE_URL_RES}/html/images/h5/1.png" id="shan-img" style="display:none;" />
    <img src="{$CDN_BASE_URL_RES}/html/images/h5/2.png" id="sorry-img" style="display:none;" />
    <div style="width:65%;margin:0 auto;text-align: center;
    margin-top: 80px;font-size: 36px;">掌玩 <br>幸运大转盘</div>
    <div class="">
      <div class="lottry-wrapper">
        <div style="display:none;" class=" five lottry">
            <img src="{$CDN_BASE_URL_RES}/html/images/h5/5.jpg" alt="">
        </div>
        <div class="close"><img src="{$CDN_BASE_URL_RES}/html/images/h5/close.png" alt=""></div>      
      </div>
      <div class="lottry-wrapper">
        <div style="display:none;" class=" ten lottry">
            <img src="{$CDN_BASE_URL_RES}/html/images/h5/10.jpg" alt="">
        </div>
        
        <div class="close"><img src="{$CDN_BASE_URL_RES}/html/images/h5/close.png" alt=""></div>      
      </div>
      <div class="lottry-wrapper ">
        <div style="display:none;" class="twenty lottry">
            <img src="{$CDN_BASE_URL_RES}/html/images/h5/20.jpg" alt="">
        </div>
        
        <div class="close"><img src="{$CDN_BASE_URL_RES}/html/images/h5/close.png" alt=""></div>      
      </div>
      <div class="lottry-wrapper ">
        <div style="display:none;" class="fifty lottry">
            <img src="{$CDN_BASE_URL_RES}/html/images/h5/50.jpg" alt="">
        </div>
        <div class="close"><img src="{$CDN_BASE_URL_RES}/html/images/h5/close.png" alt=""></div>
      </div>
    </div>
	<div class="banner">
		<div class="turnplate" style="background-image:url({$CDN_BASE_URL_RES}/html/images/h5/turnplate-bg.png);background-size:100% 100%;margin-top:30%;">
			<canvas class="item" id="wheelcanvas" width="422px" height="422px"></canvas>
			<img class="pointer" src="{$CDN_BASE_URL_RES}/html/images/h5/turnplate-pointer.png"/>
		</div>
	</div>
	<div style="width: 85%;margin: 0 auto;">
		<ul>
			<li>活动说明：</li>
			<li>1、本活动参与仅限掌玩·女神节投票助力活动的投票用户参加,一人仅限兑奖一次</li>
			<li>2、若中奖请截屏发送给掌玩客服：myy991259212（微信号），由客服充值到用户掌玩账户</li>
		</ul>
	</div>
</body>
<script type="text/javascript">
var turnplate={
		restaraunts:[],				//大转盘奖品名称
		colors:[],					//大转盘奖品区块对应背景颜色
		outsideRadius:192,			//大转盘外圆的半径
		textRadius:155,				//大转盘奖品位置距离圆心的距离
		insideRadius:68,			//大转盘内圆的半径
		startAngle:0,				//开始角度
		randomRate:[],              //控制获奖率，百分制(相加需等于100%)，对应restaraunts(顺序需要保持一致)，
		bRotate:false				//false:停止;ture:旋转
};

$(document).ready(function(){
	//动态添加大转盘的奖品与奖品区域背景颜色
	turnplate.randomRate = ["0%", '0%', '0%', '0%', '2%', '0%', '98%', '0%'];
	turnplate.restaraunts = ["50元代金券", "谢谢参与", "20元代金券", "谢谢参与", "10元代金券", "谢谢参与", "5元代金券", "谢谢参与"];
	turnplate.colors = ["#FFF4D6", "#FFFFFF", "#FFF4D6", "#FFFFFF","#FFF4D6", "#FFFFFF", "#FFF4D6", "#FFFFFF","#FFF4D6", "#FFFFFF"];
	var rotateTimeOut = function (){
		$('#wheelcanvas').rotate({
			angle:0,
			animateTo:2160,
			duration:8000,
			callback:function (){
				alert('网络超时，请检查您的网络设置！');
			}
		});
	};

	//旋转转盘 item:奖品位置; txt：提示语;
	var rotateFn = function (item, txt){
		var angles = item * (360 / turnplate.restaraunts.length) - (360 / (turnplate.restaraunts.length*2));
		if(angles<270){
			angles = 270 - angles; 
		}else{
			angles = 360 - angles + 270;
		}
		$('#wheelcanvas').stopRotate();
		$('#wheelcanvas').rotate({
			angle:0,
			animateTo:angles+1800,
			duration:8000,
			callback:function (){
				// alert(txt);

				switch(txt)
				{
				case "5元代金券":
          $(".ten").hide();
          $(".twenty").hide();
          $(".fifty").hide();
					$('.five').show();
          $(".five").parent().show()
					console.log("5元代金券")		
					break;
				case "10元代金券":
					$(".five").hide();
          $(".twenty").hide();
          $(".fifty").hide();          
          $('.ten').show(); 
          $(".ten").parent().show()     
					console.log("10元代金券")
					break;
				case "20元代金券":
					$(".ten").hide();
          $(".five").hide();
          $(".fifty").hide();
          $(".twenty").show();
          $('.twenty').parent().show();
					console.log("20元代金券")
					break;
				case "50元代金券":
					$('.fifty').show();          
          $(".ten").hide();
          $(".five").hide();
          $(".twenty").hide();
          $(".fifty").parent().show()
					console.log("50元代金券")
					break;
				case "谢谢参与":
					alert("谢谢参与")
					break;
				case "undefind":
					alert("undefind")
					break;
				}
				turnplate.bRotate = !turnplate.bRotate;
			}
		});
	};

	$('.pointer').click(function (){
		if(turnplate.bRotate)return;
		turnplate.bRotate = !turnplate.bRotate;
		//获取随机数(奖品个数范围内)
		var item = rnd(turnplate.randomRate);
		//奖品数量等于10,指针落在对应奖品区域的中心角度[252, 216, 180, 144, 108, 72, 36, 360, 324, 288]
		rotateFn(item, turnplate.restaraunts[item-1]);
	});
});

function rnd(rate){
	var random = Math.floor(Math.random() * 100);
	var myRandom = [];
	var randomList = [];
	var randomParent = [];
	for(var i = 0; i < 100; i++){
		myRandom.push(parseInt([i]) + 1);
	}
	for(var i = 0; i < rate.length; i++){
		var temp = [];
		var start = 0;
		var end = 0;
		randomList.push(parseInt(rate[i].split('%')[0]));
		for(var j = 0; j < randomList.length; j++){
			start += randomList[j-1] || 0
			end += randomList[j]
		}
		temp = myRandom.slice(start, end);
		randomParent.push(temp)
	}
	for(var i = 0; i < randomParent.length; i++){
		if($.inArray(random, randomParent[i]) > 0){
			return(i+1)
		}
	}
	
}


//页面所有元素加载完毕后执行drawRouletteWheel()方法对转盘进行渲染
window.onload=function(){
	drawRouletteWheel();
};

function drawRouletteWheel() {    
  var canvas = document.getElementById("wheelcanvas");    
  if (canvas.getContext) {
	  //根据奖品个数计算圆周角度
	  var arc = Math.PI / (turnplate.restaraunts.length/2);
	  var ctx = canvas.getContext("2d");
	  //在给定矩形内清空一个矩形
	  ctx.clearRect(0,0,422,422);
	  //strokeStyle 属性设置或返回用于笔触的颜色、渐变或模式  
	  ctx.strokeStyle = "#FFBE04";
	  //font 属性设置或返回画布上文本内容的当前字体属性
	  ctx.font = '16px Microsoft YaHei';      
	  for(var i = 0; i < turnplate.restaraunts.length; i++) {       
		  var angle = turnplate.startAngle + i * arc;
		  ctx.fillStyle = turnplate.colors[i];
		  ctx.beginPath();
		  //arc(x,y,r,起始角,结束角,绘制方向) 方法创建弧/曲线（用于创建圆或部分圆）    
		  ctx.arc(211, 211, turnplate.outsideRadius, angle, angle + arc, false);    
		  ctx.arc(211, 211, turnplate.insideRadius, angle + arc, angle, true);
		  ctx.stroke();  
		  ctx.fill();
		  //锁画布(为了保存之前的画布状态)
		  ctx.save();   
		  
		  //----绘制奖品开始----
		  ctx.fillStyle = "#E5302F";
		  var text = turnplate.restaraunts[i];
		  var line_height = 17;
		  //translate方法重新映射画布上的 (0,0) 位置
		  ctx.translate(211 + Math.cos(angle + arc / 2) * turnplate.textRadius, 211 + Math.sin(angle + arc / 2) * turnplate.textRadius);
		  
		  //rotate方法旋转当前的绘图
		  ctx.rotate(angle + arc / 2 + Math.PI / 2);
		  
		  /** 下面代码根据奖品类型、奖品名称长度渲染不同效果，如字体、颜色、图片效果。(具体根据实际情况改变) **/
		  if(text.indexOf("M")>0){//流量包
			  var texts = text.split("M");
			  for(var j = 0; j<texts.length; j++){
				  ctx.font = j == 0?'bold 20px Microsoft YaHei':'16px Microsoft YaHei';
				  if(j == 0){
					  ctx.fillText(texts[j]+"M", -ctx.measureText(texts[j]+"M").width / 2, j * line_height);
				  }else{
					  ctx.fillText(texts[j], -ctx.measureText(texts[j]).width / 2, j * line_height);
				  }
			  }
		  }else if(text.indexOf("M") == -1 && text.length>6){//奖品名称长度超过一定范围 
			  text = text.substring(0,6)+"||"+text.substring(6);
			  var texts = text.split("||");
			  for(var j = 0; j<texts.length; j++){
				  ctx.fillText(texts[j], -ctx.measureText(texts[j]).width / 2, j * line_height);
			  }
		  }else{
			  //在画布上绘制填色的文本。文本的默认颜色是黑色
			  //measureText()方法返回包含一个对象，该对象包含以像素计的指定字体宽度
			  ctx.fillText(text, -ctx.measureText(text).width / 2, 0);
		  }
		  
		  //添加对应图标
		  if(text.indexOf("代金券")>0){
			  var img= document.getElementById("shan-img");
			  img.onload=function(){  
				  ctx.drawImage(img,-15,10);      
			  }; 
			  ctx.drawImage(img,-15,10);  
		  }else if(text.indexOf("谢谢参与")>=0){
			  var img= document.getElementById("sorry-img");
			  img.onload=function(){  
				  ctx.drawImage(img,-15,10);      
			  };  
			  ctx.drawImage(img,-15,10);  
		  }
		  //把当前画布返回（调整）到上一个save()状态之前 
		  ctx.restore();
		  //----绘制奖品结束----
	  }     
  } 
}
$(".close").click(function(){
  $(this).parent().hide();
  console.log("p")
})
</script>
</html>