<!DOCTYPE html>
<html lang="zh_cn">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>拍卖会员保证金规则</title>
  <style>
    *{margin: 0;padding: 0;}
    .note {
      padding: 25px 16px;
    }
    .title {
      font-size: 16px;
      margin-bottom: 25px;
    }
    p {
      color: #1E1E1E;
      font-size: 12px;
      margin: 10px 0;
      line-height: 1.8;
    }
  </style>
</head>
<body>
  <div class="note">
    <h1 class="title">拍品会员保证金规则</h1>
    <p>1.保证金为<strong>单场保证金</strong>，缴纳后方可进入相应单场拍场参与竞拍出价；</p>
    <p>2.充值保证金进行出价仅限于商家设置的有保证金的拍卖专场，拍卖方未设置保证金的拍卖场次无需交纳保证金即可出价；</p>
    <p>3.竟拍结束后，未结缘者，平台即刻解冻保证金，资金<strong>原路退回</strong>；</p>
    <p>4.竞拍成功者，在相应的拍品订单付款后平台解冻本场保证金，资金<strong>原路退回</strong>；</p>
    <p>5.竞拍成功者若未在24小时的付款时间内支付相应的拍品订单的付款款项，系统将扣除用户所缴纳的对应该场次拍卖的保证金，补偿给对应场次的拍卖方；</p>
  </div>
</body>
</html>