<!doctype html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<title>关于我们</title>
	<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/pc/css/global.css?171201">
	<script src="{$CDN_BASE_URL_RES}/html/js/jquery.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pc/js/zhangwan.js?180305"></script>
</head>
<body>
	<!-- nav -->
	<div class="header bgc">
		<div class="container nav">
			<a href="index.html" class="f-fl logo"><img src="{$CDN_BASE_URL_RES}/html/pc/images/logo.png"></a>
			<ul>
				<li><a href="index.html">首页</a></li>
				<li><a href="headlines.html">头条</a></li>
				<li><a href="circle.html">圈子</a></li>
				<li><a href="treasure.html">寻宝</a></li>
				<li><a href="download.html">APP下载</a></li>
				<li class="on"><a href="about.html">关于我们</a></li>
			</ul>		
			<div class="clearfix f-fr search-box">
				<input type="text" placeholder="请输入关键词" class="search f-fl">
				<button class="f-fr icon submit" type="button"></button>
			</div>								
		</div>
	</div>	
	<!-- banner -->
	<div class="about-banner"></div>
	<div class="container about-tit01">
		<div class="about-tit">
			<h3>关于掌玩+</h3>
			<span>ABOUT ZHANGWAN</span>
		</div>
		<div class="jianjie clearfix">
			<img src="{$CDN_BASE_URL_RES}/html/pc/images/about.jpg" class="f-fl">
			<p><b>掌玩</b>是河南九阳网络科技有限公司开发的一款艺术品线上交易APP，致力于打造成为国内最大的艺术品电商交易平台。平台汇集书画、陶瓷、文玩等多个艺术品类，为各类艺术机构、艺术家以及收藏爱好者提供一个作品展售与信息交流的交互平台。<i>掌玩以「好货 好玩 好赚」为经营理念，聚焦书画领域，覆盖全艺术品类，结合互联网思维，在商品交易与社群运营方面，打造极致用户体验，打通艺术投资与大众生活的消费壁垒，让艺术走进更多普通人群。</i></p>
		</div>
	</div>
	<div class="bgc">
		<div class="container about-tit02">
			<div class="about-tit">
				<h3>掌玩特色+</h3>
				<span>FEATURES ZHANGWAN</span>
			</div>
			<ul class="tese clearfix">
				<li>
					<img src="{$CDN_BASE_URL_RES}/html/pc/images/about-icon1.png">
					<h3>掌玩头条</h3>
					<p>艺术资讯，包罗万象</p>
				</li>
				<li>
					<img src="{$CDN_BASE_URL_RES}/html/pc/images/about-icon2.png">
					<h3>寻宝商城</h3>
					<p>云集艺术全品，择你所爱</p>
				</li>
				<li>
					<img src="{$CDN_BASE_URL_RES}/html/pc/images/about-icon3.png">
					<h3>名家甄选</h3>
					<p>实力名家，签约入驻</p>
				</li>
				<li>
					<img src="{$CDN_BASE_URL_RES}/html/pc/images/about-icon4.png">
					<h3>私人订制</h3>
					<p>订制书画，彰显品位</p>
				</li>
				<li>
					<img src="{$CDN_BASE_URL_RES}/html/pc/images/about-icon5.png">
					<h3>兴趣社交</h3>
					<p>同道好友，在线互动</p>
				</li>
			</ul>
		</div>
	</div>
	<div class="about-banner-foot"></div>
</body>
</html>