<!doctype html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<title>APP下载</title>
		<link rel="stylesheet" href="{$CDN_BASE_URL_RES}/html/pc/css/global.css?171201"> 
	<script src="{$CDN_BASE_URL_RES}/html/js/jquery.min.js"></script>
	<script src="{$CDN_BASE_URL_RES}/html/pc/js/zhangwan.js?180305"></script>
</head>
<body class="tk2">
	<!-- nav -->
	<div class="header bgc">
		<div class="container nav">
			<a href="index.html" class="f-fl logo"><img src="{$CDN_BASE_URL_RES}/html/pc/images/logo.png"></a>
			<ul>
				<li><a href="index.html">首页</a></li>
				<li><a href="headlines.html">头条</a></li>
				<li><a href="circle.html">圈子</a></li>
				<li><a href="treasure.html">寻宝</a></li>
				<li class="on"><a href="download.html">APP下载</a></li>
				<li><a href="about.html">关于我们</a></li>
			</ul>		
			<div class="clearfix f-fr search-box">
				<input type="text" placeholder="请输入关键词" class="search f-fl">
				<button class="f-fr icon submit" type="button"></button>
			</div>								
		</div>
	</div>		
	<!-- banner -->
	<div class="banner">
		<div class="container">
			<img src="{$CDN_BASE_URL_RES}/html/pc/images/banner-iphone.png?171128" class="f-fl banner-iphone">
			<div class="f-fl tit">
				<img src="{$CDN_BASE_URL_RES}/html/pc/images/tit.png">
				<ul>
					<li><a href="javascript:void(0);" class="download-btn"><i class="icon ios"></i>iPhone</a></li>
					<li><a href="javascript:void(0);" class="download-btn"><i class="icon android"></i>Android</a></li>
				</ul>
			</div>
		</div>
	</div>
 	<div class="bgc">
 		<div class="container app-list clearfix">
 			<div class="f-tac app-tit">
 				<h3>艺术寻宝</h3>
 				<p>随时随地甄选精品</p>
 			</div>
 			<img src="{$CDN_BASE_URL_RES}/html/pc/images/phone1.png?171128" class="f-fl">
 			<div class="info f-fr">
 				<div>
 					<img src="{$CDN_BASE_URL_RES}/html/pc/images/dou.jpg" class="dou">
 				<h2>让艺术品走进<br>寻常百姓家</h2>
 				</div>
 				
 				<p>掌玩APP提供专业的艺术品交易平台</p>
 			</div>
 		</div>
 	</div>
  	<div class="bgc2">
 		<div class="container app-list clearfix">
 			<img src="{$CDN_BASE_URL_RES}/html/pc/images/phone2.png?171128" class="f-fr">
 			<div class="info f-fl">
 				<div>
 					<img src="{$CDN_BASE_URL_RES}/html/pc/images/dou2.jpg" class="dou">
 				<h2>让懂艺术的人<br>更懂你</h2>
 				</div>
 				<p>同行交流，专业的艺术品交流APP</p>
 			</div>
 		</div>
 	</div>
 	<div class="bgc">
 		<div class="container app-list clearfix">
 			<div class="f-tac app-tit">
 				<h3>个人主页</h3>
 				<p>特色主页 个人专属</p>
 			</div>
 			<img src="{$CDN_BASE_URL_RES}/html/pc/images/phone3.png?171128" class="f-fl">
 			<div class="info f-fr">
 				<div>
 					<img src="{$CDN_BASE_URL_RES}/html/pc/images/dou.jpg" class="dou">
 				<h2>不孤芳自赏，<br>有宝贝晒一晒</h2>
 				</div>
 				<p>不一样的朋友圈，不一样的艺术体验</p>
 			</div>
 		</div>
 	</div>
 	<div class="bgc2">
 		<div class="container app-list clearfix">
 			<img src="{$CDN_BASE_URL_RES}/html/pc/images/phone4.jpg?171128" class="f-fr">
 			<div class="info f-fl">
 				<div>
 					<img src="{$CDN_BASE_URL_RES}/html/pc/images/dou2.jpg" class="dou">
 				<h2>附近名家臻品<br>近在咫尺</h2>
 				</div>
 				<p>交藏友，约名家，求定制</p>
 			</div>
 		</div>
 	</div>
</body>
</html>